"""Shared test fixtures for HFEA scraper tests.

Fixtures load archived HTML files generated by html_archiver.py.
Run `python html_archiver.py` once before running the test suite.
"""

import os
import pytest
from bs4 import BeautifulSoup

ARCHIVED_HTML_DIR = os.path.join(os.path.dirname(__file__), 'archived_html')
SEARCH_RESULTS_PAGE1_PATH = os.path.join(ARCHIVED_HTML_DIR, 'search_results_page1.html')
CLINIC_DETAIL_153_PATH = os.path.join(ARCHIVED_HTML_DIR, 'clinic_detail_153.html')
CLINIC_DETAIL_BARTS_PATH = os.path.join(ARCHIVED_HTML_DIR, 'barts_detail.html')

_ARCHIVED_PATHS = [
    SEARCH_RESULTS_PAGE1_PATH,
    CLINIC_DETAIL_153_PATH,
    CLINIC_DETAIL_BARTS_PATH,
]


def _read_html(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


requires_archived_html = pytest.mark.skipif(
    not all(os.path.isfile(p) for p in _ARCHIVED_PATHS),
    reason="Archived HTML not found. Run `python html_archiver.py` first.",
)


@pytest.fixture
def search_results_html():
    """Archived search results page 1 HTML (10 clinics including satellites)."""
    return _read_html(SEARCH_RESULTS_PAGE1_PATH)


@pytest.fixture
def homerton_detail_html():
    """Archived Homerton Fertility Centre (ID 153) detail page HTML."""
    return _read_html(CLINIC_DETAIL_153_PATH)


@pytest.fixture
def barts_detail_html():
    """Archived Barts Health Centre (ID 94) detail page HTML."""
    return _read_html(CLINIC_DETAIL_BARTS_PATH)


@pytest.fixture
def homerton_soup(homerton_detail_html):
    """Parsed BeautifulSoup of Homerton detail page."""
    return BeautifulSoup(homerton_detail_html, 'lxml')


@pytest.fixture
def barts_soup(barts_detail_html):
    """Parsed BeautifulSoup of Barts detail page."""
    return BeautifulSoup(barts_detail_html, 'lxml')
