"""Unit tests for extractors.py — data extraction from HFEA clinic pages.

Tests run against archived HTML files generated by html_archiver.py.
Run `python html_archiver.py` once before running the test suite.
"""

from bs4 import BeautifulSoup

from conftest import requires_archived_html
from extractors import (
    HFEA_MISSING_DATA_PLACEHOLDER,
    extract_all_clinic_data,
    extract_birth_stats_under_38,
    extract_bmi_limit,
    extract_clinic_name,
    extract_counselling_sessions,
    extract_egg_freezing,
    extract_inspection_rating,
    extract_nhs_private,
    extract_number_of_ratings,
    extract_patient_empathy_rating,
    extract_patient_empowerment_rating,
    extract_patient_rating,
    extract_treatments_from_search_card,
    safe_float,
    safe_int,
)

# ── safe_float / safe_int ────────────────────────────────────────────────


class TestSafeFloat:
    def test_normal_number(self):
        assert safe_float("3.14") == 3.14

    def test_integer_string(self):
        assert safe_float("42") == 42.0

    def test_with_percent(self):
        assert safe_float("31%") == 31.0

    def test_with_commas(self):
        assert safe_float("1,234.5") == 1234.5

    def test_none_returns_default(self):
        assert safe_float(None) is None

    def test_empty_string_returns_default(self):
        assert safe_float("") is None

    def test_na_returns_default(self):
        assert safe_float("N/A") is None
        assert safe_float("n/a") is None
        assert safe_float("NA") is None

    def test_dash_returns_default(self):
        assert safe_float("-") is None

    def test_hfea_missing_placeholder(self):
        assert safe_float("-900") is None
        assert safe_float(str(HFEA_MISSING_DATA_PLACEHOLDER)) is None

    def test_custom_default(self):
        assert safe_float(None, default=0.0) == 0.0
        assert safe_float("bad", default=-1) == -1

    def test_whitespace_stripped(self):
        assert safe_float("  5.5  ") == 5.5

    def test_non_numeric_returns_default(self):
        assert safe_float("abc") is None


class TestSafeInt:
    def test_normal_int(self):
        assert safe_int("17") == 17

    def test_with_commas(self):
        assert safe_int("1,000") == 1000

    def test_none_returns_default(self):
        assert safe_int(None) is None

    def test_empty_returns_default(self):
        assert safe_int("") is None

    def test_na_returns_default(self):
        assert safe_int("N/A") is None

    def test_custom_default(self):
        assert safe_int(None, default=0) == 0

    def test_non_numeric_returns_default(self):
        assert safe_int("abc") is None


# ── extract_clinic_name ──────────────────────────────────────────────────


@requires_archived_html
class TestExtractClinicName:
    def test_homerton(self, homerton_soup):
        assert extract_clinic_name(homerton_soup) == "Homerton Fertility Centre"

    def test_barts(self, barts_soup):
        assert extract_clinic_name(barts_soup) == "Barts Health Centre for Reproductive Medicine"

    def test_no_h1_returns_none(self):
        soup = BeautifulSoup("<html><body><p>No heading</p></body></html>", "lxml")
        assert extract_clinic_name(soup) is None


# ── extract_bmi_limit ────────────────────────────────────────────────────


@requires_archived_html
class TestExtractBmiLimit:
    def test_homerton_has_bmi_limit(self, homerton_soup):
        # Homerton lists "BMI limit" with no specific number
        assert extract_bmi_limit(homerton_soup) is True

    def test_barts_has_bmi_limit(self, barts_soup):
        assert extract_bmi_limit(barts_soup) is True

    def test_no_eligibility_section(self):
        html = "<html><body><div>No eligibility here</div></body></html>"
        soup = BeautifulSoup(html, "lxml")
        assert extract_bmi_limit(soup) is None

    def test_eligibility_without_bmi(self):
        html = """
        <div class="detail">
            <h2>Eligibility</h2>
            <ul><li>Treats NHS patients</li></ul>
        </div>
        """
        soup = BeautifulSoup(html, "lxml")
        assert extract_bmi_limit(soup) is None

    def test_bmi_with_numeric_value(self):
        html = """
        <div class="detail">
            <h2>Eligibility</h2>
            <ul><li>BMI limit of 35</li></ul>
        </div>
        """
        soup = BeautifulSoup(html, "lxml")
        assert extract_bmi_limit(soup) == 35.0


# ── extract_egg_freezing ─────────────────────────────────────────────────


@requires_archived_html
class TestExtractEggFreezing:
    def test_homerton_offers_egg_freezing(self, homerton_soup):
        assert extract_egg_freezing(homerton_soup) is True

    def test_barts_offers_egg_freezing(self, barts_soup):
        assert extract_egg_freezing(barts_soup) is True

    def test_no_treatments_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_egg_freezing(soup) is False

    def test_treatments_without_preservation(self):
        html = """
        <div class="detail">
            <h2>Treatments</h2>
            <ul><li>IVF</li><li>ICSI</li></ul>
        </div>
        """
        soup = BeautifulSoup(html, "lxml")
        assert extract_egg_freezing(soup) is False


# ── extract_treatments_from_search_card ──────────────────────────────────


@requires_archived_html
class TestExtractTreatmentsFromSearchCard:
    def _get_card(self, search_results_html, clinic_name_fragment):
        """Find a clinic card in the search results page by name fragment."""
        soup = BeautifulSoup(search_results_html, "lxml")
        for card in soup.find_all("li", class_="clinic"):
            name_h3 = card.find("h3", class_="clinic-name")
            if name_h3 and clinic_name_fragment.lower() in name_h3.get_text().lower():
                return card
        raise ValueError(f"Card not found for: {clinic_name_fragment}")

    def test_homerton_no_ivf_icsi_surgical(self, search_results_html):
        """Homerton's search card lists no IVF/ICSI/Surgical sperm."""
        card = self._get_card(search_results_html, "Homerton")
        treatments = extract_treatments_from_search_card(card)
        assert treatments["ivf"] is False
        assert treatments["icsi"] is False
        assert treatments["surgical_sperm"] is False

    def test_create_fertility_all_treatments(self, search_results_html):
        """CREATE Fertility offers IVF, ICSI, and Surgical sperm collection."""
        card = self._get_card(search_results_html, "CREATE Fertility")
        treatments = extract_treatments_from_search_card(card)
        assert treatments["ivf"] is True
        assert treatments["icsi"] is True
        assert treatments["surgical_sperm"] is True

    def test_kings_ivf_icsi_surgical(self, search_results_html):
        """King's Fertility offers IVF, ICSI, and Surgical sperm collection."""
        card = self._get_card(search_results_html, "King")
        treatments = extract_treatments_from_search_card(card)
        assert treatments["ivf"] is True
        assert treatments["icsi"] is True
        assert treatments["surgical_sperm"] is True

    def test_satellite_has_no_treatments(self, search_results_html):
        """Satellite cards have empty treatment sections."""
        card = self._get_card(search_results_html, "Lister Fertility Clinic at The Shard")
        treatments = extract_treatments_from_search_card(card)
        assert treatments["ivf"] is False
        assert treatments["icsi"] is False
        assert treatments["surgical_sperm"] is False

    def test_sperm_bank_no_ivf(self, search_results_html):
        """London Sperm Bank only offers IUI, not IVF/ICSI/Surgical."""
        card = self._get_card(search_results_html, "London Sperm Bank")
        treatments = extract_treatments_from_search_card(card)
        assert treatments["ivf"] is False
        assert treatments["icsi"] is False
        assert treatments["surgical_sperm"] is False


# ── extract_nhs_private ──────────────────────────────────────────────────


@requires_archived_html
class TestExtractNhsPrivate:
    def test_homerton_nhs_only(self, homerton_soup):
        result = extract_nhs_private(homerton_soup)
        assert result["nhs"] is True
        assert result["private"] is False

    def test_barts_nhs_and_private(self, barts_soup):
        result = extract_nhs_private(barts_soup)
        assert result["nhs"] is True
        assert result["private"] is True

    def test_no_eligibility_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        result = extract_nhs_private(soup)
        assert result == {"nhs": False, "private": False}


# ── extract_counselling_sessions ─────────────────────────────────────────


@requires_archived_html
class TestExtractCounsellingSessions:
    def test_homerton_has_counselling(self, homerton_soup):
        assert extract_counselling_sessions(homerton_soup) is True

    def test_barts_has_counselling(self, barts_soup):
        assert extract_counselling_sessions(barts_soup) is True

    def test_no_counselling_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_counselling_sessions(soup) is False

    def test_counselling_without_included_sessions(self):
        html = """
        <div class="detail">
            <h2>Counselling and support</h2>
            <ul><li>Counselling services at clinic</li></ul>
        </div>
        """
        soup = BeautifulSoup(html, "lxml")
        assert extract_counselling_sessions(soup) is False


# ── extract_inspection_rating ────────────────────────────────────────────


@requires_archived_html
class TestExtractInspectionRating:
    def test_homerton_blank_rating(self, homerton_soup):
        """Homerton's inspection rating span is empty (licence issue)."""
        assert extract_inspection_rating(homerton_soup) is None

    def test_barts_rating_5(self, barts_soup):
        assert extract_inspection_rating(barts_soup) == 5.0

    def test_no_inspection_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_inspection_rating(soup) is None


# ── extract_patient_rating ───────────────────────────────────────────────


@requires_archived_html
class TestExtractPatientRating:
    def test_homerton_4_5(self, homerton_soup):
        assert extract_patient_rating(homerton_soup) == 4.5

    def test_barts_3(self, barts_soup):
        assert extract_patient_rating(barts_soup) == 3.0

    def test_no_patient_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_patient_rating(soup) is None


# ── extract_number_of_ratings ────────────────────────────────────────────


@requires_archived_html
class TestExtractNumberOfRatings:
    def test_homerton_17(self, homerton_soup):
        assert extract_number_of_ratings(homerton_soup) == 17

    def test_barts_9(self, barts_soup):
        assert extract_number_of_ratings(barts_soup) == 9

    def test_no_patient_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_number_of_ratings(soup) is None


# ── extract_patient_empowerment_rating ───────────────────────────────────


@requires_archived_html
class TestExtractPatientEmpowermentRating:
    def test_homerton_4_5(self, homerton_soup):
        assert extract_patient_empowerment_rating(homerton_soup) == 4.5

    def test_barts_3(self, barts_soup):
        assert extract_patient_empowerment_rating(barts_soup) == 3.0

    def test_no_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_patient_empowerment_rating(soup) is None


# ── extract_patient_empathy_rating ───────────────────────────────────────


@requires_archived_html
class TestExtractPatientEmpathyRating:
    def test_homerton_4_5(self, homerton_soup):
        assert extract_patient_empathy_rating(homerton_soup) == 4.5

    def test_barts_3(self, barts_soup):
        assert extract_patient_empathy_rating(barts_soup) == 3.0

    def test_no_section(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_patient_empathy_rating(soup) is None


# ── extract_birth_stats_under_38 ─────────────────────────────────────────


@requires_archived_html
class TestExtractBirthStatsUnder38:
    def test_homerton_stats(self, homerton_soup):
        stats = extract_birth_stats_under_38(homerton_soup)
        # ivfembryo: data-mean="31", data-min-range="24", data-max-range="38"
        assert stats["embryo_transferred_mean"] == 31.0
        assert stats["embryo_transferred_error"] == 14.0  # 38 - 24
        # ivfegg: data-mean="35", data-min-range="19", data-max-range="56"
        assert stats["egg_collection_mean"] == 35.0
        assert stats["egg_collection_error"] == 37.0  # 56 - 19
        # dibirths: data-mean="5", data-min-range="0", data-max-range="39"
        assert stats["donor_insemination_mean"] == 5.0
        assert stats["donor_insemination_error"] == 39.0  # 39 - 0

    def test_barts_stats(self, barts_soup):
        stats = extract_birth_stats_under_38(barts_soup)
        # ivfembryo: data-mean="32", data-min-range="27", data-max-range="38"
        assert stats["embryo_transferred_mean"] == 32.0
        assert stats["embryo_transferred_error"] == 11.0  # 38 - 27
        # ivfegg: data-mean="42", data-min-range="33", data-max-range="51"
        assert stats["egg_collection_mean"] == 42.0
        assert stats["egg_collection_error"] == 18.0  # 51 - 33
        # dibirths: data-mean="14", data-min-range="1", data-max-range="69"
        assert stats["donor_insemination_mean"] == 14.0
        assert stats["donor_insemination_error"] == 68.0  # 69 - 1

    def test_empty_page_returns_empty_dict(self):
        soup = BeautifulSoup("<html><body></body></html>", "lxml")
        assert extract_birth_stats_under_38(soup) == {}

    def test_hfea_missing_data_placeholder(self):
        """Data-mean of -900 should be treated as missing."""
        html = """
        <ul>
            <li>
                <span class="item">
                    <input type="radio" name="ivfembryo" checked="checked" />
                    <label data-min-range="0" data-max-range="0"
                           data-nat-ave="34" data-mean="-900" data-count="0">
                        Under 38
                    </label>
                </span>
            </li>
        </ul>
        """
        soup = BeautifulSoup(html, "lxml")
        stats = extract_birth_stats_under_38(soup)
        assert stats.get("embryo_transferred_mean") is None


# ── extract_all_clinic_data (integration) ────────────────────────────────


@requires_archived_html
class TestExtractAllClinicData:
    def test_homerton_full_extraction(self, homerton_detail_html):
        data = extract_all_clinic_data(homerton_detail_html)
        assert data["Name of clinic"] == "Homerton Fertility Centre"
        assert data["BMI eligibility limit"] is True
        assert data["Do they do egg-freezing"] is True
        assert data["Treats NHS patients"] is True
        assert data["Treats private patients"] is False
        assert data["At least one counselling session included"] is True
        assert data["Inspection rating out of 5"] is None
        assert data["Patient rating out of 5"] == 4.5
        assert data["Number of patient ratings"] == 17
        assert data["Patient empowerment rating"] == 4.5
        assert data["Patient empathy rating"] == 4.5
        assert data["Under 38s births per embryo transferred"] == 31.0
        assert data["Error bars: Under 38s births per embryo transferred"] == 14.0
        assert data["Under 38s births per egg collection"] == 35.0
        assert data["Error bars: Under 38s births per egg collection"] == 37.0
        assert data["Under 38s births per donor insemination treatment"] == 5.0
        assert data["Error bars: Under 38s births per donor insemination treatment"] == 39.0
        # Treatment fields are None when no search card provided
        assert data["Do they do IVF"] is None
        assert data["Do they do ICSI"] is None
        assert data["Do they do Surgical sperm collection"] is None

    def test_barts_full_extraction(self, barts_detail_html):
        data = extract_all_clinic_data(barts_detail_html)
        assert data["Name of clinic"] == "Barts Health Centre for Reproductive Medicine"
        assert data["BMI eligibility limit"] is True
        assert data["Do they do egg-freezing"] is True
        assert data["Treats NHS patients"] is True
        assert data["Treats private patients"] is True
        assert data["At least one counselling session included"] is True
        assert data["Inspection rating out of 5"] == 5.0
        assert data["Patient rating out of 5"] == 3.0
        assert data["Number of patient ratings"] == 9
        assert data["Patient empowerment rating"] == 3.0
        assert data["Patient empathy rating"] == 3.0
        assert data["Under 38s births per embryo transferred"] == 32.0
        assert data["Error bars: Under 38s births per embryo transferred"] == 11.0
        assert data["Under 38s births per egg collection"] == 42.0
        assert data["Error bars: Under 38s births per egg collection"] == 18.0
        assert data["Under 38s births per donor insemination treatment"] == 14.0
        assert data["Error bars: Under 38s births per donor insemination treatment"] == 68.0

    def test_with_search_card_html(self):
        """When search card HTML is provided, treatment fields are populated."""
        detail_html = "<html><body><h1>Test Clinic</h1></body></html>"
        card_html = """
        <div class="col-md-4 list">
            <h4>Treatments offered</h4>
            <ul>
                <li>IVF</li>
                <li>ICSI</li>
            </ul>
        </div>
        """
        data = extract_all_clinic_data(detail_html, search_card_html=card_html)
        assert data["Do they do IVF"] is True
        assert data["Do they do ICSI"] is True
        assert data["Do they do Surgical sperm collection"] is False
